apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nw0ok45n6-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nw0ok45n6-nodejs 
  name: nw0ok45n6-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: nw0ok45n6-nodejs 
